name: Embold Code Quality Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  embold-scan_fc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download and Extract Scanner
        run: |
          curl ${{ vars.EMBOLD_SCANNER_URL }} -o browserstack-codequality-scanner-archive.tar.gz
          tar xvf browserstack-codequality-scanner-archive.tar.gz

      - name: Download Repository Configuration
        run: |
          curl --silent --location --request GET "${{ vars.EMBOLD_URL_JAVA }}/api/v1/repositories/32ca03072749436f4f85b60caac30844/scans/config/download" \
            --header "Authorization: Bearer ${{ secrets.EMBOLD_TOKEN_JAVA }}" \
            -o repository-configuration.json

      - name: Run Embold Scanner
        env:
          EMBOLD_TOKEN: ${{ secrets.EMBOLD_TOKEN_JAVA }}
        run: |
          ./browserstack-codequality-scanner/bin/embold-scanner analyse \
            -u ${{ vars.EMBOLD_URL_JAVA }} \
            -t $EMBOLD_TOKEN \
            -r 32ca03072749436f4f85b60caac30844 \
            -b . \
            -d ./embold-data \
            -c ./repository-configuration.json \
            -l ./embold-log \
            -sh ./embold-scanner-home \
            -v
